type = "webpack"
webpack_config = "webpack.config.js"

name = "deka-collection-api"
account_id = "21f21d9f5c226ec6b0325b46209bc0d9"

kv_namespaces = [
	{ binding = "ACCOUNTS", id = "b38e56fc71d942e6a2ab982972e3ad96", preview_id = "b38e56fc71d942e6a2ab982972e3ad96" }
]

workers_dev = true

[env.production]
workers_dev = false
zone_id = "10c8e82d4b989bf095668d43da5068ec"
route = "https://deka.narusejun.com/api/*"

kv_namespaces = [
	{ binding = "ACCOUNTS", id = "b38e56fc71d942e6a2ab982972e3ad96", preview_id = "b38e56fc71d942e6a2ab982972e3ad96" }
]
